# Name of your application. Used to uniquely configure containers.
service: nachimaitsexpense

# Name of the container image.
image: nachiket87/nachimaitsexpense

# Deploy to these servers.
servers:
  - 142.93.67.87


env:
  secret:
    - DATABASE_URL

registry:
  username: nachiket87
  password:
   - KAMAL_REGISTRY_PASSWORD

accessories:
 db:
   image: postgres:14.0
   host: 142.93.67.87
   port: 5432
   env:
     secret:
       - NACHIMAITSEXPENSE_DATABASE_PASSWORD

healthcheck:
  path: /up
  port: 3000
