# Name of your application. Used to uniquely configure containers.
service: nachimaitsexpense

# Name of the container image.
image: nachiket87/nachimaitsexpense

# Deploy to these servers.
servers:
  - 142.93.67.87


env:
  secret:
    - DATABASE_URL

registry:
  username: nachiket87
  password:
   - KAMAL_REGISTRY_PASSWORD

accessories:
 db:
   image: postgres:14.0
   host: db.internal
   port: 5432
   env:
     secret:
       - NACHIMAITSEXPENSE_DATABASE_PASSWORD
hooks:
  pre_build:
    - command: bin/rails assets:precompile
  post_deploy:
    - command: bin/rails db:migrate
    - command: bin/rails cache:clear

healthcheck:
  path: /up
  port: 3000
